version: "3.8"

services:
  sqlserver-container:
    container_name: sqlserver-container
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin@1234
    ports:
      - "1433:1433"
    networks:
      - shopapp-asp-network
    volumes:
      - sqlserver-data:/var/opt/mssql

  # oracledb:
  #   image: container-registry.oracle.com/database/standard:latest
  #   container_name: oracle-standard-container
  #   shm_size: '8gb'
  #   restart: unless-stopped
  #   ports:
  #     - 1522:1521
  #   env_file:
  #     - oracle_db_env.dat

  #   volumes:
  #     - ./db:/opt/oracle/oradata

  asp-web-container:
    container_name: asp-web-container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MSSQL_SA_PASSWORD=Admin@1234
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver-container
    networks:
      - shopapp-asp-network

volumes:
  sqlserver-data:
    driver: local

networks:
  shopapp-asp-network:
    name: shopapp-asp-network
    driver: bridge
    external: true
# docker-compose -f ./deployment.yaml down
# docker-compose -f ./deployment.yaml up -d

# kiểm tra xem có container nào sử dụng network không
# docker network inspect shopapp-asp-network
# docker network create shopapp-asp-network

# khởi tạo database
# docker-compose -f ./deployment.yaml rm -s -f sqlserver-container
# docker-compose -f ./deployment.yaml up -d sqlserver-container

# truy cập vào database
# sqlcmd -S localhost -U SA -P "Admin@1234"

# kiểm tra tất cả database
# EXEC sp_databases;
# GO

# tạo image docker asp web
# docker-compose -f ./deployment.yaml rm -s -f asp-web-container
# docker-compose -f ./deployment.yaml up -d asp-web-container

# kiểm tra network
# docker network ls
# docker network inspect 07e49996e124
